# Generated by Django 3.2 on 2021-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20210513_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
