# Generated by Django 3.2 on 2021-05-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
